셜커_HP: 5

월드_설정:
    # 월드 명
    world:
        # 카테고리(a~b) x 아이템(c~d) = 셜커 상자에 뜰 아이템 개수  * (a~b), (c~d): 각 최소 ~ 최대 범위
        # e.g. 카테고리(2~2) x 아이템(3~4) = 6~8
        # (최소)~(최대)
        카테고리: 1~1
        아이템: 4~4
    # 월드 명
    SPAWN-2:
        # 카테고리(a~b) x 아이템(c~d) = 셜커 상자에 뜰 아이템 개수  * (a~b), (c~d): 각 최소 ~ 최대 범위
        # e.g. 카테고리(2~2) x 아이템(3~4) = 6~8
        # (최소)~(최대)
        카테고리: 1~1
        아이템: 2~2
