파밍셜커:
    # 파밍 셜커 활성화 할 월드 목록
    적용할월드_목록: []

    # 카테고리(a~b) x 아이템(c~d) = 셜커에 뜰 아이템 개수  * (a~b), (c~d): 각 최소 ~ 최대 범위
    # e.g. 카테고리(2~2) x 아이템(3~4) = 6~8
    아이템_개수_범위:
        # (최소)~(최대)
        카테고리: 0~0
        아이템: 0~0
